spring:
  application:
    name: challenge
  datasource:
    url: jdbc:h2:mem:exchangedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: alan
    password: alan
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8099
  
exchange:
  url: https://v6.exchangerate-api.com/v6/cf1d218e235fde2732a18ac6/latest